project_id = "jdjreuxhvzmzockuduyq"

[functions.market-maker]
verify_jwt = true

[functions.delete-whitelist]
verify_jwt = true

[functions.unblacklist-user]
verify_jwt = true

[functions.check-blacklist]
verify_jwt = false

[functions.manage-admin-wallets]
verify_jwt = true

[functions.redemptions]
verify_jwt = false

[functions.verify-admin]
verify_jwt = false

[functions.deposits]
verify_jwt = false

[functions.verify-admin-wallet]
verify_jwt = false

[functions.get-market-maker-config]
verify_jwt = true

[functions.update-market-maker-config]
verify_jwt = true

[functions.whitelist-requests]
verify_jwt = false

[functions.approve-whitelist]
verify_jwt = true

[functions.check-whitelist]
verify_jwt = false

[functions.admin-deposits]
verify_jwt = true

[functions.admin-redemptions]
verify_jwt = true

[functions.approve-deposit]
verify_jwt = true

[functions.blacklist-user]
verify_jwt = true

[functions.get-bank-reserves]
verify_jwt = true

[functions.update-bank-reserves]
verify_jwt = true