project_id = "jdjreuxhvzmzockuduyq"

[functions.market-maker]
verify_jwt = true

[functions.redemptions]
verify_jwt = true

[functions.verify-admin]
verify_jwt = false

[functions.get-market-maker-config]
verify_jwt = false

[functions.update-market-maker-config]
verify_jwt = false